import "./globals.css"

import { Footer } from "@/components/footer"
import { Header } from "@/components/header"
import { Inter } from "next/font/google"
import type { Metadata } from "next"
import Providers from "@/app/providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "IFCalc",
  description: "Generated by create next app",
  icons: "/icon.svg",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className}`}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex flex-col flex-1 relative container mt-20 mb-4 space-y-4">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}